//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcClient.VacancyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vacancy", Namespace="http://schemas.datacontract.org/2004/07/VacancyServiceInterface")]
    [System.SerializableAttribute()]
    public partial class Vacancy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Requirement {
            get {
                return this.RequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementField, value) != true)) {
                    this.RequirementField = value;
                    this.RaisePropertyChanged("Requirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Responsibility {
            get {
                return this.ResponsibilityField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsibilityField, value) != true)) {
                    this.ResponsibilityField = value;
                    this.RaisePropertyChanged("Responsibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VacancyServiceReference.IVacancyService")]
    public interface IVacancyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacancyService/GetOnlineVacancies", ReplyAction="http://tempuri.org/IVacancyService/GetOnlineVacanciesResponse")]
        MvcClient.VacancyServiceReference.Vacancy[] GetOnlineVacancies(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacancyService/GetOnlineVacancies", ReplyAction="http://tempuri.org/IVacancyService/GetOnlineVacanciesResponse")]
        System.Threading.Tasks.Task<MvcClient.VacancyServiceReference.Vacancy[]> GetOnlineVacanciesAsync(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacancyService/GetLocalVacancies", ReplyAction="http://tempuri.org/IVacancyService/GetLocalVacanciesResponse")]
        MvcClient.VacancyServiceReference.Vacancy[] GetLocalVacancies(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacancyService/GetLocalVacancies", ReplyAction="http://tempuri.org/IVacancyService/GetLocalVacanciesResponse")]
        System.Threading.Tasks.Task<MvcClient.VacancyServiceReference.Vacancy[]> GetLocalVacanciesAsync(string searchText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVacancyServiceChannel : MvcClient.VacancyServiceReference.IVacancyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VacancyServiceClient : System.ServiceModel.ClientBase<MvcClient.VacancyServiceReference.IVacancyService>, MvcClient.VacancyServiceReference.IVacancyService {
        
        public VacancyServiceClient() {
        }
        
        public VacancyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VacancyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacancyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacancyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcClient.VacancyServiceReference.Vacancy[] GetOnlineVacancies(string searchText) {
            return base.Channel.GetOnlineVacancies(searchText);
        }
        
        public System.Threading.Tasks.Task<MvcClient.VacancyServiceReference.Vacancy[]> GetOnlineVacanciesAsync(string searchText) {
            return base.Channel.GetOnlineVacanciesAsync(searchText);
        }
        
        public MvcClient.VacancyServiceReference.Vacancy[] GetLocalVacancies(string searchText) {
            return base.Channel.GetLocalVacancies(searchText);
        }
        
        public System.Threading.Tasks.Task<MvcClient.VacancyServiceReference.Vacancy[]> GetLocalVacanciesAsync(string searchText) {
            return base.Channel.GetLocalVacanciesAsync(searchText);
        }
    }
}
