SET IDENTITY_INSERT [dbo].[Nationality] ON
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (1, N'<Undefined>         ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (2, N'Argentinian         ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (3, N'Australian          ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (4, N'Belgian             ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (5, N'Canadian            ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (6, N'Chinese             ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (7, N'Danish              ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (8, N'English             ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (9, N'French              ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (10, N'German              ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (11, N'Dutch               ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (12, N'Indian              ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (13, N'Japanese            ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (14, N'Mexican             ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (15, N'Norwegian           ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (16, N'Polish              ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (17, N'Russian             ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (18, N'Singaporean         ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (19, N'Thai                ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (20, N'US                  ')
INSERT INTO [dbo].[Nationality] ([id], [Alias]) VALUES (21, N'Uzbek               ')
SET IDENTITY_INSERT [dbo].[Nationality] OFF
